// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:b9f83104093cedc63c837de44e1e69cdbaedfd307b34a160d54db036d206560a'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:555373498e19e57cf50852bccbd2d386bfbbe82186c9909709bf61f8a7852b67'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly settings: {
      readonly id: Char<36>;
      readonly keywords: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly blacklist_keywords: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly min_budget: CodecTypes['pg/text@1']['output'];
      readonly max_proposal_count: CodecTypes['pg/int4@1']['output'];
    };
    readonly works: {
      readonly id: Char<36>;
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly link: CodecTypes['pg/text@1']['output'];
      readonly description_summary: CodecTypes['pg/text@1']['output'] | null;
      readonly budget: CodecTypes['pg/text@1']['output'] | null;
      readonly hourly_rate: CodecTypes['pg/text@1']['output'] | null;
      readonly proposal_count: CodecTypes['pg/int4@1']['output'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly published_at: CodecTypes['pg/timestamptz@1']['output'];
      readonly status: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly settings: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly keywords: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly blacklist_keywords: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly min_budget: CodecTypes['pg/text@1']['input'];
      readonly max_proposal_count: CodecTypes['pg/int4@1']['input'];
    };
    readonly works: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly link: CodecTypes['pg/text@1']['input'];
      readonly description_summary: CodecTypes['pg/text@1']['input'] | null;
      readonly budget: CodecTypes['pg/text@1']['input'] | null;
      readonly hourly_rate: CodecTypes['pg/text@1']['input'] | null;
      readonly proposal_count: CodecTypes['pg/int4@1']['input'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly published_at: CodecTypes['pg/timestamptz@1']['input'];
      readonly status: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly settings: {
      readonly blacklist_keywords: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly id: Char<36>;
      readonly keywords: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly max_proposal_count: CodecTypes['pg/int4@1']['output'];
      readonly min_budget: CodecTypes['pg/text@1']['output'];
    };
    readonly works: {
      readonly budget: CodecTypes['pg/text@1']['output'] | null;
      readonly description_summary: CodecTypes['pg/text@1']['output'] | null;
      readonly hourly_rate: CodecTypes['pg/text@1']['output'] | null;
      readonly id: Char<36>;
      readonly link: CodecTypes['pg/text@1']['output'];
      readonly proposal_count: CodecTypes['pg/int4@1']['output'];
      readonly published_at: CodecTypes['pg/timestamptz@1']['output'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly status: CodecTypes['pg/text@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly settings: {
      readonly blacklist_keywords: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly keywords: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly max_proposal_count: CodecTypes['pg/int4@1']['input'];
      readonly min_budget: CodecTypes['pg/text@1']['input'];
    };
    readonly works: {
      readonly budget: CodecTypes['pg/text@1']['input'] | null;
      readonly description_summary: CodecTypes['pg/text@1']['input'] | null;
      readonly hourly_rate: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly link: CodecTypes['pg/text@1']['input'];
      readonly proposal_count: CodecTypes['pg/int4@1']['input'];
      readonly published_at: CodecTypes['pg/timestamptz@1']['input'];
      readonly skills: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly status: CodecTypes['pg/text@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly settings: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly keywords: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly blacklist_keywords: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly min_budget: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly max_proposal_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly works: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly link: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description_summary: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly budget: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly hourly_rate: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly proposal_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly skills: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly published_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['link'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly works: { readonly namespace: 'public' & NamespaceId; readonly model: 'works' };
    readonly settings: { readonly namespace: 'public' & NamespaceId; readonly model: 'settings' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly settings: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly keywords: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly blacklist_keywords: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly min_budget: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly max_proposal_count: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'settings';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly keywords: { readonly column: 'keywords' };
                readonly blacklist_keywords: { readonly column: 'blacklist_keywords' };
                readonly min_budget: { readonly column: 'min_budget' };
                readonly max_proposal_count: { readonly column: 'max_proposal_count' };
              };
            };
          };
          readonly works: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly link: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description_summary: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly budget: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly hourly_rate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly proposal_count: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly skills: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly published_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'works';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly link: { readonly column: 'link' };
                readonly description_summary: { readonly column: 'description_summary' };
                readonly budget: { readonly column: 'budget' };
                readonly hourly_rate: { readonly column: 'hourly_rate' };
                readonly proposal_count: { readonly column: 'proposal_count' };
                readonly skills: { readonly column: 'skills' };
                readonly published_at: { readonly column: 'published_at' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'settings';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'works';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
